# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Francesco Spinnato
title: Ph.D. Candidate, Researcher
email: francesco.spinnato@sns.it
website: https://github.com/fspinna/

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: fspinna
github_username:  fspinna
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: francesco-spinnato
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
orcid_username: 0000-0002-3203-6716

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I am a Ph.D. candidate in Data Science at Scuola Normale Superiore, and a researcher at the University of Pisa. 
  My research focus is on explainable AI for sequential data, in particular on interpreting black-box models for univariate and multivariate time series. 
  In 2017, I received my B.S. degree in Economics and Management at the University of Padua, Italy, and in 2020 my M.S. degree in Data Science at the University of Pisa, Italy.


# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
